name: Build and Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis

      # Run SonarQube scan
      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_b909a81178736b683f43c3d04f21b8616dfce09d
          SONAR_HOST_URL: http://47.128.78.109:9000

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      # Cache Trivy vulnerability database
      - name: Cache Trivy vulnerability database
        uses: actions/cache@v2
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      # Run Trivy file system scan
      - name: Run Trivy file system scan
        run: |
          # Ensure the DB is downloaded (if not available in the cache)
          trivy fs --download-db-only || true
          # Perform a file system scan
          trivy fs .

      # Docker build and push
      - name: Docker build and push
        run: |
          docker build --build-arg TMDB_V3_API_KEY=e1464541c6df1f01cdc5b44e1bd3b74c -t netflix .
          docker tag netflix muvinmuthuramalingam2017/netflix:latest
          docker login -u muvinmuthuramalingam2017 -p dckr_pat_22YL5xAoSw0LWlijatpjgO8oM4g
          docker push muvinmuthuramalingam2017/netflix:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Install Trivy (again in the deploy job)
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      # Pull Docker image
      - name: Pull the Docker image
        run: docker pull muvinmuthuramalingam2017/netflix:latest

      # Run Trivy scan with retries (to handle rate limits)
      - name: Run Trivy image scan
        run: |
          for i in {1..5}; do
            trivy image muvinmuthuramalingam2017/netflix:latest && break || sleep 30;
          done

      # Run the Docker container
      - name: Run the container
        run: docker run -d --name netflix -p 8081:80 muvinmuthuramalingam2017/netflix:latest
